local t = require("tests.framework")
local envelope = require("fcs.envelope")
t.test("clamps a field to its positive cap", function()
  local d = envelope.clamp({ pitch = 5, roll = -5 }, { pitch = 0.2, roll = 0.2 })
  t.near(d.pitch, 0.2, 1e-9); t.near(d.roll, -0.2, 1e-9)
end)
t.test("passes fields with no cap through unchanged", function()
  local d = envelope.clamp({ heave = 0.9, yaw = 0.1 }, { yaw = 1 })
  t.near(d.heave, 0.9, 1e-9); t.near(d.yaw, 0.1, 1e-9)
end)
t.test("leaves in-range values untouched", function()
  t.near(envelope.clamp({ sway = 0.05 }, { sway = 0.5 }).sway, 0.05, 1e-9)
end)
t.test("a non-finite demand (NaN or inf) maps to 0 -- never forwarded to the mixer", function()
  local nan = 0 / 0
  local d = envelope.clamp({ pitch = nan, roll = math.huge, yaw = -math.huge, heave = 0.5 },
                           { pitch = 0.2, roll = 0.2, yaw = 0.6 })
  t.eq(d.pitch, 0); t.eq(d.roll, 0); t.eq(d.yaw, 0)   -- guarded, not clamped-through
  t.near(d.heave, 0.5, 1e-9)                            -- finite values still pass
end)

t.test("clamp reports WHICH axes were clipped (second return)", function()
  local d, sat = envelope.clamp({ pitch = 5, roll = -5, yaw = 0.01 }, { pitch = 0.2, roll = 0.2 })
  t.eq(sat.pitch, true); t.eq(sat.roll, true)
  t.eq(sat.yaw, nil, "unclipped axis is not flagged")
end)
t.test("no clipping -> sat is nil (zero garbage on the common path)", function()
  local d, sat = envelope.clamp({ pitch = 0.1 }, { pitch = 0.2 })
  t.eq(sat, nil)
end)
