local t = require("tests.framework")
local Mixer = require("fcs.mixer.level_flight")
t.test("pure heave = equal duties, no moment", function()
  local d = Mixer.new():mix({ heave = 0.5, pitch = 0, roll = 0 })
  t.near(d.FL, 0.5, 1e-9); t.near(d.FR, 0.5, 1e-9); t.near(d.RL, 0.5, 1e-9); t.near(d.RR, 0.5, 1e-9)
end)
t.test("nose-up pitch raises front duties, lowers rear", function()
  local d = Mixer.new():mix({ heave = 0.5, pitch = 0.1, roll = 0 })
  t.near(d.FL, 0.6, 1e-9); t.near(d.RL, 0.4, 1e-9)
end)
t.test("duties clamp to [0,1]", function()
  -- roll=0, so no differential to preserve; a pure over-collective just clips.
  local d = Mixer.new():mix({ heave = 1.0, pitch = 0, roll = 0 })
  t.near(d.FL, 1.0, 1e-9); t.near(d.FR, 1.0, 1e-9); t.near(d.RL, 1.0, 1e-9); t.near(d.RR, 1.0, 1e-9)
end)
-- Attitude-priority (airmode) mixing: when the collective drives a lift thruster past a
-- rail, shift the COLLECTIVE (all four equally) to bring it in range and PRESERVE the
-- pitch/roll differential (= the attitude torque). Flight #5 flipped because the old
-- per-thruster clamp silently zeroed roll authority whenever heave hit its band floor/ceiling.
t.test("low collective preserves full roll differential", function()
  -- heave at the band floor with a full roll demand: old mixer gave FL-FR = 0.25 (authority lost);
  -- airmode must give the commanded 2*roll = 0.40.
  local d = Mixer.new():mix({ heave = 0.05, pitch = 0, roll = 0.2 })
  t.near(d.FL - d.FR, 0.4, 1e-9, "front roll torque")
  t.near(d.RL - d.RR, 0.4, 1e-9, "rear roll torque")
  t.truthy(d.FR >= -1e-9 and d.FL <= 1 + 1e-9, "in range")
end)
t.test("high collective preserves full roll differential", function()
  local d = Mixer.new():mix({ heave = 0.85, pitch = 0, roll = 0.2 })
  t.near(d.FL - d.FR, 0.4, 1e-9, "front roll torque")
  t.near(d.RL - d.RR, 0.4, 1e-9, "rear roll torque")
  t.truthy(d.FL <= 1 + 1e-9 and d.RR >= -1e-9, "in range")
end)
t.test("in-range demands pass through unchanged", function()
  local d = Mixer.new():mix({ heave = 0.5, pitch = 0.1, roll = 0.05 })
  t.near(d.FL, 0.65, 1e-9); t.near(d.FR, 0.55, 1e-9)
  t.near(d.RL, 0.45, 1e-9); t.near(d.RR, 0.35, 1e-9)
end)
t.test("unsatisfiable differential scales pitch and roll together", function()
  -- span of raw duties = 1.6 > 1, so both axes scale by 1/1.6 = 0.625; ratio preserved.
  local d = Mixer.new():mix({ heave = 0.5, pitch = 0.4, roll = 0.4 })
  t.near(d.FL - d.RL, 0.5, 1e-9, "pitch torque (2*p*scale)")
  t.near(d.FL - d.FR, 0.5, 1e-9, "roll torque (2*r*scale)")
  t.truthy(d.FL <= 1 + 1e-9 and d.RR >= -1e-9, "in range")
end)
t.test("airmode leaves lateral and surge thrusters untouched", function()
  local d = Mixer.new():mix({ heave = 0.05, pitch = 0, roll = 0.2, sway = 0.3, yaw = 0.1, surge = 0.4 })
  t.truthy(d.YFL ~= nil and d.MAIN ~= nil, "lateral/surge present")
  t.near(d.MAIN, 0.4, 1e-9, "surge unchanged by airmode")
end)

t.test("zero CoM offset is byte-identical to the symmetric mix", function()
  local m = Mixer.new()
  m:setCom({ fwd = 0, right = 0, span = 4 })
  local d = m:mix({ heave = 0.5, pitch = 0.1, roll = 0.05 })
  t.near(d.FL, 0.65, 1e-9); t.near(d.FR, 0.55, 1e-9)
  t.near(d.RL, 0.45, 1e-9); t.near(d.RR, 0.35, 1e-9)
end)

t.test("CoM forward raises front heave and lowers rear (level hover, no tilt demand)", function()
  local m = Mixer.new()
  m:setCom({ fwd = 1, right = 0, span = 4 })
  local d = m:mix({ heave = 0.4, pitch = 0, roll = 0 })
  t.truthy(d.FL > d.RL, "front > rear")
  t.near(d.FL, d.FR, 1e-9, "no roll split")
  t.near((d.FL + d.FR + d.RL + d.RR) / 4, 0.4, 1e-9, "mean heave preserved")
end)

t.test("CoM right raises right heave and lowers left", function()
  local m = Mixer.new()
  m:setCom({ fwd = 0, right = 1, span = 4 })
  local d = m:mix({ heave = 0.4, pitch = 0, roll = 0 })
  t.truthy(d.FR > d.FL, "right > left")
  t.near(d.FL, d.RL, 1e-9, "no pitch split")
end)

t.test("offsetFromDuties inverts a CoM-forward mix back to fwd", function()
  local m = Mixer.new()
  m:setCom({ fwd = 0.8, right = 0, span = 4 })
  local d = m:mix({ heave = 0.4, pitch = 0, roll = 0 })
  local off = Mixer.offsetFromDuties(d, 4)
  t.near(off.fwd, 0.8, 1e-6)
  t.near(off.right, 0, 1e-6)
end)

t.test("rectangle: longer FWD span than LAT span uses independent arms", function()
  local m = Mixer.new()
  m:setCom({ fwd = 1.2, right = 0.4, spanFwd = 6, spanRight = 3 })
  local d = m:mix({ heave = 0.4, pitch = 0, roll = 0 })
  local off = Mixer.offsetFromDuties(d, { spanFwd = 6, spanRight = 3 })
  t.near(off.fwd, 1.2, 1e-5)
  t.near(off.right, 0.4, 1e-5)
end)

t.test("keepwarm OFF (warm=false) reproduces the plain mix byte-for-byte", function()
  local m = Mixer.new(); m:setKeepWarm({ floor = 0.08, surgeFront = 0.07, mainRatio = 0.05 })
  local a = m:mix({ heave = 0.5, pitch = 0, roll = 0, sway = 0.2, yaw = 0.1, surge = -0.3 }, false)
  local b = m:mix({ heave = 0.5, pitch = 0, roll = 0, sway = 0.2, yaw = 0.1, surge = -0.3 })  -- no warm arg
  for _, id in ipairs({ "YFL","YFR","YRL","YRR","MAIN","FRL","FRR" }) do
    t.near(a[id], b[id], 1e-9, id .. " identical with warm=false")
  end
end)
t.test("keepwarm ON keeps every yaw-ring thruster >= floor", function()
  local m = Mixer.new(); m:setKeepWarm({ floor = 0.08, surgeFront = 0.07, mainRatio = 0.05 })
  local out = m:mix({ heave = 0.5, sway = 0.2, yaw = 0.0, surge = 0 }, true)
  for _, id in ipairs({ "YFL","YFR","YRL","YRR" }) do
    t.truthy(out[id] >= 0.08 - 1e-9, id .. " warm (>= floor)")
  end
end)
t.test("keepwarm ON preserves net sway force and net yaw torque", function()
  local m = Mixer.new(); m:setKeepWarm({ floor = 0.08, surgeFront = 0.07, mainRatio = 0.05 })
  local function netSway(o) return (o.YFL + o.YRL) - (o.YFR + o.YRR) end   -- SWAY_DIR
  local function netYaw(o)  return (o.YFL - o.YFR) - (o.YRL - o.YRR) end   -- YAW_DIR (+,-,-,+)
  local cold = m:mix({ heave = 0.5, sway = 0.15, yaw = 0.1, surge = 0 }, false)
  local warm = m:mix({ heave = 0.5, sway = 0.15, yaw = 0.1, surge = 0 }, true)
  t.near(netSway(warm), netSway(cold), 1e-9, "net sway unchanged")
  t.near(netYaw(warm),  netYaw(cold),  1e-9, "net yaw unchanged")
end)
