package.path = "/?.lua;/?/init.lua;" .. package.path
local t = require("tests.framework")
local TD = require("fcs.io.tuningdefaults")

t.test("tuning defaults expose gains/caps/feel as a deep-copied table", function()
  local a, b = TD.get(), TD.get()
  t.eq(type(a.gains), "table")
  t.eq(type(a.caps), "table")
  t.eq(type(a.feel), "table")
  a.gains.__scratch = 1
  t.eq(b.gains.__scratch, nil, "get() returns an independent copy")
  t.truthy(a.gains.yaw and a.caps.pitch and a.feel.climbRate, "carries known keys")
end)

t.test("tuning defaults include com fwd/right/span", function()
  local d = TD.get()
  t.eq(d.com.fwd, 0)
  t.eq(d.com.right, 0)
  t.eq(d.com.spanFwd, 0)
  t.eq(d.com.spanRight, 0)
end)

t.test("tiltBrake enabled for CRU/MAN/DRN, disabled for PRE/LDG, with curve defaults", function()
  local D = require("fcs.io.tuningdefaults").get()
  -- base (PRECISION reads top-level feel) is disabled
  t.eq(D.feel.tiltBrake.enabled, false, "base/PRE disabled")
  t.near(D.feel.tiltBrake.engageSpeed, 30.0, 1e-9)
  t.near(D.feel.tiltBrake.satSpeed, 100.0, 1e-9)
  t.near(D.feel.tiltBrake.minAngle, 0.2618, 1e-4)
  t.near(D.feel.tiltBrake.maxAngle, 0.5236, 1e-4)
  t.near(D.feel.tiltBrake.buttonMax, 0.7854, 1e-4)
  t.eq(D.modes.CRUISE.feel.tiltBrake.enabled, true, "CRU enabled")
  t.eq(D.modes.MAN.feel.tiltBrake.enabled, true, "MAN enabled")
  t.eq(D.modes.DRN.feel.tiltBrake.enabled, true, "DRN enabled")
  t.eq(D.modes.LDG.feel.tiltBrake.enabled, false, "LDG disabled")
end)
