package.path = "/?.lua;/?/init.lua;" .. package.path
local t = require("tests.framework")
local TD = require("fcs.io.tuningdefaults")

t.test("tuning defaults expose gains/caps/feel as a deep-copied table", function()
  local a, b = TD.get(), TD.get()
  t.eq(type(a.gains), "table")
  t.eq(type(a.caps), "table")
  t.eq(type(a.feel), "table")
  a.gains.__scratch = 1
  t.eq(b.gains.__scratch, nil, "get() returns an independent copy")
  t.truthy(a.gains.yaw and a.caps.pitch and a.feel.climbRate, "carries known keys")
end)

t.test("tuning defaults include com fwd/right/span", function()
  local d = TD.get()
  t.eq(d.com.fwd, 0)
  t.eq(d.com.right, 0)
  t.eq(d.com.spanFwd, 0)
  t.eq(d.com.spanRight, 0)
end)

t.test("tuning defaults include the top-level emrcvr block with all 7 fields", function()
  local d = TD.get().emrcvr
  t.eq(type(d), "table", "emrcvr block present")
  t.near(d.tripAngle, 1.309, 1e-9)
  t.near(d.exitAngle, 0.175, 1e-9)
  t.near(d.maxDrift, 2.0, 1e-9)
  t.near(d.dwell, 0.5, 1e-9)
  t.near(d.levelBand, 0.5, 1e-9)
  t.near(d.kpAtt, 0.6, 1e-9)
  t.near(d.capAtt, 0.8, 1e-9)
end)

t.test("tiltBrake enabled for CRU/MAN/DRN, disabled for PRE/LDG, with curve defaults", function()
  local D = require("fcs.io.tuningdefaults").get()
  -- base (PRECISION reads top-level feel) is disabled
  t.eq(D.feel.tiltBrake.enabled, false, "base/PRE disabled")
  t.near(D.feel.tiltBrake.engageSpeed, 30.0, 1e-9)
  t.near(D.feel.tiltBrake.satSpeed, 100.0, 1e-9)
  t.near(D.feel.tiltBrake.minAngle, 0.2618, 1e-4)
  t.near(D.feel.tiltBrake.maxAngle, 0.5236, 1e-4)
  t.near(D.feel.tiltBrake.buttonMax, 0.7854, 1e-4)
  t.near(D.feel.tiltBrake.slewRate, 0.3, 1e-9, "base slewRate first-estimate")
  t.near(D.modes.CRUISE.feel.tiltBrake.slewRate, 0.3, 1e-9, "CRU inherits slewRate")
  t.near(D.modes.MAN.feel.tiltBrake.slewRate, 0.3, 1e-9, "MAN inherits slewRate")
  t.near(D.modes.DRN.feel.tiltBrake.slewRate, 0.3, 1e-9, "DRN inherits slewRate")
  t.eq(D.modes.CRUISE.feel.tiltBrake.enabled, true, "CRU enabled")
  t.eq(D.modes.MAN.feel.tiltBrake.enabled, true, "MAN enabled")
  t.eq(D.modes.DRN.feel.tiltBrake.enabled, true, "DRN enabled")
  t.eq(D.modes.LDG.feel.tiltBrake.enabled, false, "LDG disabled")
end)

t.test("sway/surge gains are the velocity-limited-hold pair {ks, ka}", function()
  local g = require("fcs.io.tuningdefaults").get().gains
  t.near(g.sway.ks, 0.4, 1e-9, "base sway ks")
  t.near(g.sway.ka, 1.0, 1e-9, "base sway ka")
  t.near(g.surge.ks, 0.4, 1e-9, "base surge ks")
  t.near(g.surge.ka, 1.0, 1e-9, "base surge ka")
  t.truthy(g.sway.kp == nil and g.sway.kd == nil, "old sway PD gains dropped")
  t.truthy(g.surge.kp == nil and g.surge.kd == nil, "old surge PD gains dropped")
end)

t.test("per-mode sway/surge ks overrides (CRU hotter, LDG gentler)", function()
  local m = require("fcs.io.tuningdefaults").get().modes
  t.near(m.CRUISE.gains.sway.ks, 0.5, 1e-9, "CRU sway ks")
  t.near(m.CRUISE.gains.surge.ks, 0.4, 1e-9, "CRU surge ks")
  t.near(m.LDG.gains.sway.ks, 0.3, 1e-9, "LDG sway ks")
  t.near(m.LDG.gains.surge.ks, 0.3, 1e-9, "LDG surge ks")
  t.near(m.LDG.gains.sway.ka, 1.0, 1e-9, "LDG sway ka inherits base")
end)

t.test("defaults expose a keepWarm block with floor/surgeFront/mainRatio", function()
  local d = require("fcs.io.tuningdefaults").get()
  t.truthy(d.keepWarm, "keepWarm present")
  t.truthy(d.keepWarm.floor and d.keepWarm.floor > 0, "floor set")
  t.truthy(d.keepWarm.surgeFront and d.keepWarm.surgeFront > 0, "surgeFront set")
  t.near(d.keepWarm.mainRatio, 0.0494, 0.005, "mainRatio ~ 2*wFront/wMain")
end)

t.test("defaults expose a decouple block (translation->attitude FF), stripped off", function()
  local d = require("fcs.io.tuningdefaults").get()
  t.truthy(d.decouple, "decouple present")
  t.near(d.decouple.swayRoll, 0, 1e-9, "swayRoll stripped to 0 (was 0.10)")
  t.near(d.decouple.surgePitch, 0, 1e-9, "surgePitch stripped to 0 (was -0.05)")
  t.near(d.decouple.authority, 0.3, 1e-9, "authority preserved for revival")
end)
t.test("LDG attitude gains stiffened for disturbance rejection", function()
  local d = require("fcs.io.tuningdefaults").get()
  t.near(d.modes.LDG.gains.pitch.kp, 0.16, 1e-9)
  t.near(d.modes.LDG.gains.roll.kp, 0.16, 1e-9)
end)
