local t = require("tests.framework")
local Looprec = require("fcs.bringup.looprec")
t.test("looprec accumulates dt in order; drain returns + clears", function()
  local r = Looprec.new(100)
  r:put(0.05); r:put(0.06); r:put(0.05)
  t.eq(r:count(), 3)
  local s = r:drain()
  t.near(s[1], 0.05, 1e-9); t.near(s[2], 0.06, 1e-9); t.near(s[3], 0.05, 1e-9)
  t.eq(r:count(), 0, "drain clears the buffer")
  t.eq(#r:drain(), 0, "second drain is empty")
end)
t.test("looprec safety cap drops oldest (no unbounded growth if stream stalls)", function()
  local r = Looprec.new(3)
  for i=1,5 do r:put(i/100) end   -- 0.01..0.05, cap 3 keeps most-recent 0.03,0.04,0.05
  t.eq(r:count(), 3)
  local s = r:drain(); t.near(s[1], 0.03, 1e-9); t.near(s[3], 0.05, 1e-9)
end)
