local t = require("tests.framework")
local ft = require("fcs.fueltable")
t.test("fueltable: baseline + default", function()
  t.eq(ft.BASELINE_PCT, 60, "baseline 60")
  t.eq(ft.default, "Biodiesel", "default Biodiesel")
end)
t.test("fueltable: scaleFor", function()
  t.near(ft.scaleFor("Biodiesel"), 1.0, 1e-9, "biodiesel 1.0")
  t.near(ft.scaleFor("Ethanol"), 0.30, 1e-9, "ethanol 0.30")
  t.near(ft.scaleFor("Plant Oil"), 3.0, 1e-9, "plant oil 3.0")
  t.near(ft.scaleFor("Gasoline"), 0.48, 1e-9, "gasoline 0.48")
  t.eq(ft.scaleFor("Nonsense"), nil, "unknown -> nil")
end)
t.test("fueltable: isBad only sub-baseline", function()
  t.eq(ft.isBad("Plant Oil"), true, "20% bad")
  t.eq(ft.isBad("Turpentine"), true, "30% bad")
  t.eq(ft.isBad("Biodiesel"), false, "60% ok")
  t.eq(ft.isBad("Diesel"), false, "80% ok")
  t.eq(ft.isBad("Nonsense"), false, "unknown not bad")
end)
t.test("fueltable: options list all 8 with percents", function()
  local o = ft.options()
  t.eq(#o, 8, "8 options")
  t.eq(o[3].value, "Biodiesel", "order: biodiesel 3rd")
  t.eq(o[3].text, "Biodiesel 60%", "label has percent")
end)

t.test("abbrevOf maps known fuels and falls back for unknown", function()
  local ft = require("fcs.fueltable")
  t.eq(ft.abbrevOf("Biodiesel"), "BDSL")
  t.eq(ft.abbrevOf("Diesel"), "DSL")
  t.eq(ft.abbrevOf("Sulfurized Diesel"), "SDSL")
  t.eq(ft.abbrevOf("Gasoline"), "GAS")
  t.eq(ft.abbrevOf("Mystery Fuel"), "MYST")     -- unknown -> first 4 upper
  t.eq(ft.abbrevOf(nil), ft.abbrevOf(ft.default)) -- nil -> default fuel's abbrev
end)
